# This file is used to replace building alias to exact building name for geocoding API. 

NAH: "Humanities Building"
SWC: "Shaw College Lecture Theatre"
UCA: "Tsang Shiu Tim Building"
UCC: "T.C. Cheng Building"
WLS: "Wen Lan Tang"
BMS: "Basic Medical Sciences Building"
SWH: "Swire Hall"
ICS: "Institute of Chinese Studies"
LSB: "Lady Shaw Building"
LSK: "Lee Shau Kee Building"
KKB: "Leung Kau Kui Building"
LDS: "Li Dak Sum Building"
MMW: "Mong Man Wai Building"
SC: "Science Centre"
TYW: "T.Y. Wong Hall"
ERB: "William M.W. Mong Engineering Building"
LHC: "Y.C. Liang Hall"
CKB: "Chen Kou Bun Building"
CYT: "Cheng Yu Tung Building"
ELB: "Esther Lee Building"
HTB: "Ho Tim Building"
HYS: "Hui Yeung Shing Building"
LKC: "Li Koon Chun Hall"
SB: "Sino Building"
SHB: "Ho Sin Hang Engineering Building"
FYB: "Wong Foo Yuan Building"
WMY: "Wu Ho Man Yuen Building"
YIA: "Yasumoto International Academic Park"
ARC: "Lee Shau Kee Architecture Building"
CK TSE: "C.K. Tse Room"
LPN: "Lai Chan Pui Ngong"

