# This file is used to replace building alias to exact building name for geocoding API. 

NAH: "Humanities Building, 人文館(新亞書院)"
SWC: "Shaw College Lecture Theatre, 大講堂(逸夫書院)"
UCA: "Tsang Shiu Tim Building, 曾肇添樓(聯合書院)"
UCC: "T.C. Cheng Building, 鄭棟材樓(聯合書院)"
WLS: "Wen Lan Tang, 文瀾堂(逸夫書院)"
BMS: "Basic Medical Sciences Building, 基本醫學大樓"
SWH: "Swire Hall, 太古堂(馮景禧樓)"
ICS: "Institute of Chinese Studies, 中國文化研究所"
LSB: "Lady Shaw Building, 邵逸夫夫人樓"
LSK: "Lee Shau Kee Building, 李兆基樓"
KKB: "Leung Kau Kui Building, 梁銶琚樓"
LDS: "Li Dak Sum Building, 李達三樓"
MMW: "Mong Man Wai Building, 蒙民偉樓"
SC: "Faculty of Science, The Chinese University of Hong Kong"
TYW: "T.Y. Wong Hall, 王統元堂(何善衡工程大樓)"
ERB: "William M.W. Mong Engineering Building, 蒙民偉工程學大樓"
LHC: "Y.C. Liang Hall, 潤昌堂"
CKB: "Chen Kou Bun Building, 陳國本樓"
CYT: "Cheng Yu Tung Building, CUHK, 鄭裕彤樓"
ELB: "Esther Lee Building, 利黃瑤璧樓"
HTB: "Ho Tim Building, 何添樓"
HYS: "Hui Yeung Shing Building, 許讓成樓"
LKC: "Li Koon Chun Hall, 李冠春堂(信和樓)"
SB: "Sino Building, 信和樓"
SHB: "Ho Sin Hang Engineering Building, 何善衡工程大樓"
FYB: "Wong Foo Yuan Building, 王福元樓"
WMY: "Wu Ho Man Yuen Building, 伍何曼原樓"
YIA: "Yasumoto International Academic Park, 康本國際學術園"
ARC: "Lee Shau Kee Architecture Building, 李兆基建築學大樓"
CK TSE: "C.K. Tse Room (Chung Chi Library), 謝昭杰室(崇基圖書館)"
LPN: "Y.C. Liang Hall, 潤昌堂"

