development:
  adapter: async

test:
  adapter: test

production:
  adapter: <%= ENV["REDIS_URL"] ? "redis" : "async" %> # pending: set REDIS_URL in Render
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: proj_production
