default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: kevin    
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: proj_development

test:
  <<: *default
  database: proj_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>
  # Ensure we don't try to connect via socket if URL is present
  host: <%= ENV["DATABASE_URL"] ? URI.parse(ENV["DATABASE_URL"]).host : nil %>
  port: <%= ENV["DATABASE_URL"] ? URI.parse(ENV["DATABASE_URL"]).port : nil %>
